version: '3.9'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal

  php:
    build: 
      context: ./build/php
      dockerfile: .
    volumes:
      - ./web:/var/www/html
    networks:
      - internal

  mysql:
    build:
      context: ./build/mysql
      dockerfile: .
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=example_db
    ports:
      - "3306:3306"
    networks:
      - internal
networks:
  internal:
    driver: bridge