version: '3.9'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal

  php:
    image: php:7.4-fpm
    volumes:
      - ./web:/var/www/html
    networks:
      - internal
networks:
  internal:
    driver: bridge